name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  tagged-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 17.x
      - run: npx yarn install
      - run: npx yarn build
      - run: tar -zcvf build-${{ github.ref_name }}.tar.gz ./build
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            build-*.tar.gz
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SCP_HOST }}
          key: ${{ secrets.SCP_RSA_KEY }}
          source: "build-*.tar.gz"
          target: "release"
